on:
  pull_request:
    types: [closed]
    branches:
      - master

name: Deploy to Deta
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: BogDAAAMN/deta-deploy-action@v1.0.1
        with:
          deta-access-token: ${{ secrets.DETA_TOKEN }}
          deta-name: "grimore"
          deta-project: "default"
